const repoUrl = 'https://github.com/AK-Lmn/ChemKit'

const tools = [
  { number: '06', symbol: 'Ee', name: 'Element Explorer', category: 'Elements', iconType: 'grid', accent: '#4dd8e8', description: 'A full interactive periodic table for browsing, searching, and studying every element at a glance.', features: ['Search elements by name or symbol', 'Filter by category', 'Favorite elements for quick recall', 'View detailed atomic data'], liveUrl: 'https://elemkit.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/PeriodicTable' },
  { number: '12', symbol: 'Mm', name: 'MoleMate', category: 'Calculations', iconType: 'molecule', accent: '#a875ff', description: 'A mole calculator that turns mass and molar mass into moles and particle counts in one step.', features: ['Calculates moles from mass and molar mass', 'Supports mg, g, and kg', "Shows particle count via Avogadro's number", 'Saves calculation history locally'], liveUrl: 'https://molemate.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/mole-calc' },
  { number: '18', symbol: 'Gl', name: 'GasLab', category: 'Calculations', iconType: 'flask', accent: '#5b9dff', description: 'A guided gas laws calculator that walks you through the setup and shows the formula behind every answer.', features: ["Boyle's, Charles's, Gay-Lussac's & Avogadro's Laws", 'Ideal Gas Law included', 'Guided inputs with a formula card per law', 'Built-in validation and clean results'], liveUrl: 'https://gaskit.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/GasLawCalc' },
  { number: '01', symbol: 'pH', name: 'pH Calculator', category: 'Solutions', iconType: 'drop', accent: '#7ce6c4', description: 'Move between pH, pOH, and ion concentration instantly with a focused calculator built for quick conversions.', features: ['Convert between pH and pOH', 'Calculate hydrogen and hydroxide ion concentration', 'Clean, fast layout for quick checks', 'Built for classroom and lab use'], liveUrl: 'https://phcalc.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/pH-Calculator' },
  { number: '20', symbol: 'Sl', name: 'SolutionLab', category: 'Solutions', iconType: 'beaker', accent: '#ffcf5a', description: 'Solve common solution concentration problems including molarity, dilution, mass concentration, and percent concentration.', features: ['Calculate molarity, moles, and volume', 'Solve dilution problems with M1V1 = M2V2', 'Work with g/L, % w/w, and % v/v', 'Includes validation, explanations, and recent history'], liveUrl: 'https://solutionlab.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/Solution-Lab' },
  { number: '—', symbol: 'Eb', name: 'Chemical Equation Balancer', category: 'Equations', iconType: 'balance', accent: '#ff8f70', description: 'Balance chemical equations and compare atom counts without trial-and-error guessing.', features: ['Supports common formulas and parentheses', 'Balances equations with exact whole-number coefficients', 'Shows coefficients and atom count tables', 'Saves recent equations locally'], liveUrl: 'https://chem-balancer.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/Chem-Balancer' },
  { number: '—', symbol: 'Ss', name: 'Stoichiometry Solver', category: 'Equations', iconType: 'ratio', accent: '#d08cff', description: 'Use balanced equations to convert between moles and grams with guided stoichiometry steps.', features: ['Supports mole-to-mole and gram-to-gram conversions', 'Calculates molar mass from formulas', 'Uses balanced-equation mole ratios', 'Shows step-by-step solutions'], liveUrl: 'https://stoichiometry-solver.vercel.app/', repoUrl: 'https://github.com/AK-Lmn/Stoichiometry-Solver' },
]

const toolGuide = [
  ['Need element data?', 'Element Explorer.'], ['Need moles or particles?', 'MoleMate.'], ['Need gas law variables?', 'GasLab.'], ['Need pH, pOH, or ion concentration?', 'pH Calculator.'], ['Need molarity, dilution, or percent concentration?', 'SolutionLab.'], ['Need to balance a chemical equation?', 'Chemical Equation Balancer.'], ['Need mole or gram conversions from an equation?', 'Stoichiometry Solver.'],
]

const whyCards = [
  { icon: 'cap', title: 'Student-friendly', accent: '#a875ff', description: "Written for the moment you're stuck on a problem set, not for people who already know the answer." },
  { icon: 'atoms', title: 'Built from real study tools', accent: '#5b9dff', description: 'Each app started as something used to pass an actual chemistry class, then got refined into a product.' },
  { icon: 'steps', title: 'Clean UI, guided calculations', accent: '#a875ff', description: 'Every calculator shows its formula and its steps, so the answer is never a black box.' },
]

const futureTools = ['Formula reference', 'Unit converter', 'Percent yield', 'Limiting reactant']

function AtomMark({ id = 'brand' }) {
  return <svg viewBox="0 0 32 32" aria-hidden="true"><defs><linearGradient id={id} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#4dd8e8"/><stop offset="1" stopColor="#5b9dff"/></linearGradient></defs><rect width="32" height="32" rx="8" fill="#0a0e1a"/><g fill="none" stroke={`url(#${id})`} strokeWidth="1.5"><ellipse cx="16" cy="16" rx="11" ry="4.4"/><ellipse cx="16" cy="16" rx="11" ry="4.4" transform="rotate(60 16 16)"/><ellipse cx="16" cy="16" rx="11" ry="4.4" transform="rotate(120 16 16)"/></g><circle cx="16" cy="16" r="3" fill="#4dd8e8"/></svg>
}

function GithubIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.57.1.78-.25.78-.55v-2.15c-3.2.7-3.87-1.36-3.87-1.36-.53-1.34-1.29-1.7-1.29-1.7-1.05-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.03 1.77 2.71 1.26 3.37.96.1-.75.4-1.26.73-1.55-2.55-.29-5.23-1.28-5.23-5.68 0-1.26.45-2.28 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11 11 0 0 1 5.79 0c2.2-1.49 3.17-1.18 3.17-1.18.64 1.59.24 2.76.12 3.05.74.81 1.18 1.83 1.18 3.09 0 4.41-2.69 5.38-5.25 5.67.41.36.78 1.08.78 2.17v3.22c0 .31.21.66.79.55A10.51 10.51 0 0 0 23.5 12C23.5 5.65 18.35.5 12 .5Z"/></svg> }

function Icon({ type }) {
  const paths = { grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>, molecule: <><circle cx="12" cy="12" r="3"/><circle cx="4" cy="7" r="2"/><circle cx="20" cy="6" r="2"/><circle cx="18" cy="20" r="2"/><path d="m6 8 3.5 2M15 10l3.4-2.5m-4 7 2.5 3.8"/></>, flask: <><path d="M8 2h8m-6 0v7L4 20a2 2 0 0 0 1.7 3h12.6a2 2 0 0 0 1.7-3L14 9V2"/><circle cx="9" cy="18" r="1"/><circle cx="15" cy="16" r="1"/></>, drop: <><path d="M12 2S5 10 5 16a7 7 0 0 0 14 0c0-6-7-14-7-14Z"/><path d="M8.5 17.5a4 4 0 0 0 3.5 2"/></>, beaker: <><path d="M6 2h12m-10 0v6L4 20a2 2 0 0 0 1.8 3h12.4A2 2 0 0 0 20 20L16 8V2M6 17h12"/></>, balance: <><path d="M2 8h16m-4-4 4 4-4 4m8 4H6m4-4-4 4 4 4"/></>, ratio: <><circle cx="5" cy="12" r="3"/><path d="M8 12h9m-4-4 4 4-4 4m7-9v10m3-8h-6m6 6h-6"/></>, cap: <><path d="m12 3-10 5 10 5 10-5-10-5Z"/><path d="M6 11v5c0 1.5 2.7 3 6 3s6-1.5 6-3v-5"/></>, atoms: <><circle cx="12" cy="12" r="3"/><circle cx="5" cy="6" r="1.5"/><circle cx="19" cy="6" r="1.5"/><circle cx="5" cy="18" r="1.5"/><circle cx="19" cy="18" r="1.5"/><path d="m9.5 10-3-3m8 3 3-3m-8 7-3 3m8-3 3 3"/></>, steps: <><path d="M4 19V6a2 2 0 0 1 2-2h9l5 5v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z"/><path d="M14 4v5h5M9 13h6m-6 4h6"/></> }
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[type]}</svg>
}

function Navbar() { return <header className="nav"><nav className="shell nav-inner" aria-label="Main navigation"><a className="brand" href="#top" aria-label="ChemKit home"><span className="brand-mark"><AtomMark/></span><span>ChemKit</span></a><div className="nav-links"><a href="#story">Story</a><a href="#tools">Tools</a><a href="#why">Why ChemKit</a></div><a className="github-pill" href={repoUrl} target="_blank" rel="noreferrer"><GithubIcon/><span>GitHub</span></a></nav></header> }

function Hero() { return <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">A chemistry toolkit, not a textbook</p><h1>Chemistry feels lighter<br/><span>with the right tools.</span></h1><p className="hero-text">ChemKit is a student-built chemistry toolkit for quick calculations, guided practice, and clean study support.</p><div className="button-row"><a className="button primary" href="#tools">Explore all 7 tools <span aria-hidden="true">↓</span></a><a className="button secondary" href={repoUrl} target="_blank" rel="noreferrer"><GithubIcon/>View GitHub</a></div><div className="hero-meta"><span><i/>7 active tools</span><span>No sign-up</span><span>Free to use</span></div></div><div className="hero-visual" aria-hidden="true"><div className="element-card"><span className="atomic">06</span><strong>Ck</strong><span>ChemKit</span></div><div className="orbit orbit-one"><i/></div><div className="orbit orbit-two"><i/></div><div className="orbit orbit-three"><i/></div></div></section> }

function StorySection() { return <section className="section shell compact" id="story"><div className="glass-panel story-panel"><div><p className="eyebrow">The story</p><h2>From capstone project<br/>to ChemKit</h2></div><p>ChemKit started as my SHS capstone project, originally made as a chemistry guide for incoming Grade 12 students. I recently rebuilt and rebranded it into a cleaner set of browser-based tools for elements, moles, gas laws, pH, and solution concentration.</p></div></section> }

function ToolGuideSection() { return <section className="section shell guide-section"><div className="section-heading"><p className="eyebrow">Find your tool</p><h2>Which tool should I use?</h2><p>Start with what you need to solve. We’ll point you in the right direction.</p></div><div className="guide-grid">{toolGuide.map(([need, tool], i) => <div className="guide-item" key={tool}><span>{String(i + 1).padStart(2, '0')}</span><p><strong>{need}</strong><br/>Use {tool}</p></div>)}</div></section> }

function ToolCard({ tool }) { return <article className="tool-card" style={{ '--accent': tool.accent }}><div className="card-top"><span>{tool.number}</span><span className="live"><i/>Live</span></div><div className="card-identity"><div className="tool-icon"><Icon type={tool.iconType}/></div><strong>{tool.symbol}</strong></div><span className="category">{tool.category}</span><h3>{tool.name}</h3><p className="card-description">{tool.description}</p><ul>{tool.features.map(feature => <li key={feature}>{feature}</li>)}</ul><div className="card-actions"><a className="button primary" href={tool.liveUrl} target="_blank" rel="noreferrer">Open Tool <span aria-hidden="true">↗</span></a><a className="button icon-button" href={tool.repoUrl} target="_blank" rel="noreferrer" aria-label={`View ${tool.name} repository`}><GithubIcon/></a></div></article> }

function ToolsSection() { return <section className="section shell" id="tools"><div className="section-heading centered"><p className="eyebrow">The toolkit</p><h2>Seven tools. One goal:<br/>get you unstuck.</h2><p>Each one solves a single problem well — no clutter, no sign-up walls, no ads.</p><div className="chips">{['Elements','Calculations','Equations','Solutions'].map(x => <span key={x}>{x}</span>)}</div></div><div className="tools-grid">{tools.map(tool => <ToolCard tool={tool} key={tool.name}/>)}</div></section> }

function WhySection() { return <section className="section shell" id="why"><div className="section-heading"><p className="eyebrow">Why ChemKit</p><h2>Built for students who struggle<br/>with chemistry, just like I did.</h2></div><div className="why-grid">{whyCards.map(card => <article className="why-card" key={card.title} style={{ '--accent': card.accent }}><div className="tool-icon"><Icon type={card.icon}/></div><h3>{card.title}</h3><p>{card.description}</p></article>)}</div></section> }

function FutureSection() { return <section className="section shell compact" id="roadmap"><div className="glass-panel future-panel"><div><p className="eyebrow">What’s next</p><h2>Still growing</h2><p>ChemKit will keep expanding with small, focused chemistry tools made for quick checks and guided practice.</p></div><div><span className="future-label">Potential future tools</span><ul>{futureTools.map(tool => <li key={tool}><i/>{tool}</li>)}</ul></div></div></section> }

function Footer() { return <footer><div className="shell footer-inner"><div className="brand"><span className="brand-mark"><AtomMark id="footer-gradient"/></span><span><strong>ChemKit</strong><small>Chemistry Tools</small></span></div><p>Made by <a href="https://github.com/AK-Lmn" target="_blank" rel="noreferrer">@AK-Lmn</a></p><a href="#top">Back to top ↑</a></div></footer> }

function App() { return <><div className="background" aria-hidden="true"><i/><i/><i/></div><Navbar/><main><Hero/><StorySection/><ToolGuideSection/><ToolsSection/><WhySection/><FutureSection/></main><Footer/></> }

export default App
